# Generated by Django 3.1.6 on 2021-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('ip_type', models.CharField(max_length=16)),
                ('continent_code', models.CharField(max_length=2)),
                ('continent_name', models.CharField(max_length=32)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=64)),
                ('region_code', models.CharField(max_length=2)),
                ('region_name', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('zip', models.CharField(max_length=16)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
            ],
        ),
    ]
