# Generated by Django 3.1.6 on 2021-02-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_geolocdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocdata',
            name='ip_type',
            field=models.CharField(max_length=4),
        ),
    ]
