# Generated by Django 3.1.6 on 2021-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_auto_20210211_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocdata',
            name='ip',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
